<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Post;
use Doctrine\ORM\EntityRepository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */


class GenreRepository extends EntityRepository
{
    public function alphabeticalQueryBuilder()
    {
        return $this->createQueryBuilder('genre')
            ->orderBy('genre.name', 'ASC');
    }
}
