<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Post;
use Doctrine\ORM\EntityRepository;

/**
 * PostCommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */


class PostCommentRepository extends EntityRepository
{
    public function findAllRecentComments(Post $post)
    {
        return $this->createQueryBuilder('post_comment')
            ->andWhere('post_comment.post = :post')
            ->setParameter('post', $post)
            ->andWhere('post_comment.createdAt > :recentDate')
            ->setParameter('recentDate', new \DateTime('-3 month'))
            ->getQuery()
            ->execute();
    }
}
