app:
    resource: '@AppBundle/Controller/'
    type: annotation
home:
    path: /
    defaults:
      _controller: AppBundle:Home:home
blog:
    path: /blog
    defaults:
      _controller: AppBundle:Blog:blog
delete_new_post:
    path: /blog/create_new_post
    defaults:
      _controller: AppBundle:Blog:createNewPost
post:
    path: /blog/{title}
    defaults:
      _controller: AppBundle:Blog:post
admin_post:
    path: /admin/post
    defaults:
        _controller: AppBundle:Admin/PostAdmin:postAdmin
admin_new:
    path: /admin/post/new
    defaults:
        _controller: AppBundle:Admin/PostAdmin:new
admin_edit:
    path: /admin/post/{id}/edit
    defaults:
        _controller: AppBundle:Admin/PostAdmin:edit
security_login:
    path: /login
    defaults:
        _controller: AppBundle:Security:login
security_logout:
    path: /logout
    defaults:
        _contoller: AppBundle:Security:logout
user_register:
    path: /register
    defaults:
        _controller: AppBundle:User:register